export { default as EyeIcon } from "assets/eye-icon.svg"
export { default as EyeOffIcon } from "assets/eye-off-icon.svg"
export { default as SearchIcon} from "assets/search-icon.svg"
export { default as LocationIcon } from "assets/location-icon.svg"
export { default as CreateEventIcon } from "assets/create-event.svg"
export { default as HomeIcon } from "assets/home-icon.svg"
export { default as UserTestImg } from "assets/test.png"
export { default as ProfileIcon } from "assets/profile-icon.svg"
export { default as MyEventsIcon } from "assets/events-icon.svg"
export { default as HistoryIcon } from "assets/history-icon.svg"
export { default as SettingsIcon } from "assets/settings-icon.svg"
export { default as InfoIcon } from "assets/info-icon.svg"
export { default as AboutIcon } from "assets/youtube.svg"
export { default as FacebookIcon } from "assets/facebook.svg"
export { default as InstagramIcon } from "assets/instagram.svg"
export { default as TikTokIcon } from "assets/tik-tok.svg"
export { default as XIcon } from "assets/twitter-alt-circle.svg"
export { default as YoutubeIcon } from "assets/youtube.svg"

